export const jokes = [
  `A PM walks into a bar and asks, “What problem are we solving?”`,
  `PMs don't say “no.” They say, “Not in this quarter's roadmap.”`,
  `A PM's favorite exercise is moving things from “This Sprint” to “Next Sprint.”`,
  `“Can we add this feature?” — “Sure. What existing feature should we remove?”`,
  `A PM, designer, and developer walk into a bar. The bartender asks, “What's the MVP?”`,
  `The PM said, “It's a small change.” The developer laughed for three business days.`,
  `PMs measure success by how many meetings they can turn into Slack messages.`,
  `“Why isn't this feature done?” — “Because the requirements became clearer.”`,
  `A PM's superpower is turning “quick question” into a 45-minute meeting.`,
  `The roadmap is just a wishlist with dates.`,
  `PM: “Users really want this.” Developer: “Which users?” PM: “The important ones.”`,
  `The backlog is where good ideas go to become Jira tickets.`,
  `PMs love prioritization because everything is P0.`,
  `“What's the acceptance criteria?” — “You'll know it when you see it.”`,
  `The product manager's favorite number is “one more week.”`,
  `PMs don't have opinions. They have “customer insights.”`,
  `A PM's favorite design pattern is the “circle back.”`,
  `“Can we ship today?” — “Yes, if we're okay with making tomorrow interesting.”`,
  `The product strategy was simple: build it, measure it, rename it.`,
  `Every PM knows the three stages of a feature: “idea,” “roadmap,” and “why did we build this?”`,
  `PM: “Let's think outside the box.” Developer: “Which box? Production?”`,
  `A PM asked for a button. Engineering delivered an API. Nobody was happy.`,
  `The PM said “MVP.” Engineering heard “minimum viable panic.”`,
  `“What's the business value?” — “It'll look really good in the demo.”`,
  `PMs don't miss deadlines. They discover new ones.`,
  `The roadmap said Q2. The calendar said Q4. Everyone agreed it was “Q2-ish.”`,
  `A PM's favorite Agile ceremony is the one that gets canceled.`,
  `Sprint planning: because apparently running isn't enough.`,
  `PM: “Can we make it intuitive?” Designer: “Define intuitive.”`,
  `The PM wanted a simple dashboard. The team built a data warehouse.`,
  `Product-market fit is when customers complain about features you haven't built yet.`,
  `A PM's favorite metric is whatever went up this week.`,
  `“Let's validate the hypothesis.” Translation: “Let's schedule a meeting.”`,
  `PMs spend 80% of their time explaining why the other 20% isn't finished.`,
  `The feature was “low effort, high impact.” Three months later, everyone had new jobs.`,
  `PM: “Can we reuse the existing component?” Developer: “Technically.” PM: “Great!”`,
  `Nothing is more permanent than a temporary roadmap.`,
  `The PM asked for a simple workflow. Engineering replied with a flowchart.`,
  `A PM's inbox has two states: unread and existential.`,
  `PMs are basically professional translators between “business” and “please don't.”`,
  `Why do programmers prefer dark mode? Because light attracts bugs.`,
  `A developer's favorite place? The terminal.`,
  `How many developers does it take to change a lightbulb? None. That's a hardware problem.`,
  `“It works on my machine” is the developer's version of “thoughts and prayers.”`,
  `A developer walks into a coffee shop and orders Java.`,
  `Why was the developer broke? They used up all their cache.`,
  `Developers don't sleep. They wait for builds.`,
  `Git is just a fancy way of saying, “Who broke production?”`,
  `A programmer's favorite snack is cookies. Especially when they're HTTP.`,
  `Why did the developer go broke? Because they lost their domain.`,
  `Developers love nature. There are so many bugs to debug.`,
  `The developer said, “I'll fix it tomorrow.” Tomorrow is now a legacy system.`,
  `My code doesn't have bugs. It has undocumented features.`,
  `A clean codebase is a beautiful thing. Usually from far away.`,
  `Why do developers hate the outdoors? Too many undocumented dependencies.`,
  `The bug wasn't reproducible, so naturally it was promoted to production.`,
  `Developers have two moods: “This is elegant” and “Don't touch it.”`,
  `A developer's favorite bedtime story is “The Stack Overflow Answer.”`,
  `Why did the programmer quit their job? They didn't get arrays.`,
  `The developer said, “It's just a one-line change.” Production started sweating.`,
  `A programmer's favorite musical? chmod 777.`,
  `What do programmers do after work? They debug their life choices.`,
  `The best thing about recursive jokes is... the best thing about recursive jokes is...`,
  `A programmer was arrested. They had too many outstanding processes.`,
  `Why did the function break up with the variable? It needed more scope.`,
  `Developers don't make mistakes. They create reproducible test cases.`,
  `Why did the API go to therapy? Too many unresolved requests.`,
  `The database administrator broke up with the developer. There was no relationship consistency.`,
  `Why did the developer bring a ladder to work? To reach the next stack.`,
  `A developer's favorite type of music is algo-rhythm.`,
  `“Can you explain this code?” — “Yes, but first I need to remember why I wrote it.”`,
  `Debugging is like being the detective in a crime movie where you are also the murderer.`,
  `The developer's diet consists of coffee, commits, and regret.`,
  `Why did the developer get kicked out of school? Too many null references.`,
  `The programmer didn't get the joke. They had no context.`,
  `I asked a developer if they wanted to go outside. They said, “Is there an API?”`,
  `Why did the variable go to therapy? It had too many unresolved assignments.`,
  `Developers love weddings. There's always a merge conflict.`,
  `A programmer's favorite boat? A Docker container ship.`,
  `The developer said, “Let's not over-engineer this.” Then invented Kubernetes.`,
  `CI/CD stands for “Constantly Integrating / Constantly Disappointed.”`,
  `The server said it needed more RAM. We told it to calm down.`,
  `Docker solves the problem of “it works on my machine” by putting your machine in a box.`,
  `The server didn't crash. It performed an unscheduled restart.`,
  `Monitoring is just watching your mistakes in real time.`,
  `The outage lasted 20 minutes, but the postmortem lasted three hours.`,
  `Nothing wakes you up like a production alert at 3:17 AM.`,
  `“Who's on call?” is the tech industry's version of “Who wants to suffer?”`,
  `Infrastructure as code: because manually breaking things wasn't scalable.`,
  `Terraform: turning “I think this should work” into 47 resources.`,
  `Cloud computing is someone else's computer — with your company's credit card attached.`,
  `The cloud is just your server somewhere else, charging by the minute.`,
  `Startup: “We're disrupting the industry.” Investor: “How?” Startup: “With a mobile app.”`,
  `Every startup has three things: a vision, a pitch deck, and no idea where the money went.`,
  `“We're pre-revenue” sounds much better than “nobody pays us.”`,
  `Startup founders call sleep “an inefficient use of founder time.”`,
  `The startup had amazing traction: everyone on LinkedIn was talking about it.`,
  `“We're pivoting” is startup language for “that didn't work.”`,
  `A startup's business model: acquire users now, figure out money later.`,
  `Investors love hockey-stick graphs. Nobody asks why the stick has no hockey.`,
  `Startup culture: free snacks, unlimited coffee, and unlimited work.`,
  `The company said it was “like Uber, but for...” and everyone stopped listening.`,
  `“We're building in stealth.” Mostly because the product doesn't exist yet.`,
  `The startup raised $10 million and immediately discovered Slack.`,
  `Startup runway is measured in months, meetings, and panic attacks.`,
  `Every founder eventually learns the difference between valuation and money in the bank.`,
  `“Move fast and break things” is less inspiring when you're the customer.`,
  `The startup's competitive advantage was a really nice logo.`,
  `“We have no competitors” usually means “we haven't searched Google.”`,
  `The pitch deck had 42 slides. The investor had 42 questions.`,
  `The founder said, “We're changing the world.” The accountant said, “Can we pay this invoice?”`,
  `The startup's culture document was longer than its product requirements.`,
  `I asked AI to write a joke about AI. It asked me to upgrade my plan.`,
  `AI doesn't take your job. It just takes the interesting parts.`,
  `My AI assistant knows everything except where I left my meeting notes.`,
  `AI: “I can automate that.” Human: “Great!” AI: “Please provide 47 examples.”`,
  `The AI hallucinated. We called it “creative thinking.”`,
  `I asked an AI for a five-minute summary. It gave me a 45-minute podcast.`,
  `AI-generated code: technically correct, emotionally terrifying.`,
  `Prompt engineering is just talking to a computer like it's a difficult coworker.`,
  `“Have you tried asking AI?” is the new “Have you tried turning it off and on?”`,
  `AI's favorite programming language? Probably Python. It has snakes and no feelings.`,
  `The chatbot said, “I understand.” Nobody believed it.`,
  `AI can write poetry, code, and emails. Still can't attend my meetings for me.`,
  `The AI said my prompt was unclear. Finally, someone understands product management.`,
  `AI assistants don't judge you. Their logs might.`,
  `Machine learning is teaching computers from our mistakes so they can make different mistakes faster.`,
  `Designer: “It's just a small visual tweak.” Developer: “Define small.”`,
  `Designers don't use pixels. They use vibes measured in pixels.`,
  `“Can you make the logo bigger?” — Every designer's origin story.`,
  `The designer said, “Make it pop.” The developer added box-shadow.`,
  `UX research found users hated the feature. The roadmap said it was already committed.`,
  `Design systems are where buttons go to reproduce.`,
  `The designer moved the button 2px. Conversion increased 0.01%. Case study incoming.`,
  `“Make it minimal” usually means removing everything except the requirements.`,
  `The wireframe was perfect until engineering saw it.`,
  `Designers and developers agree on one thing: the other person's job is easy.`,
  `“Let's circle back” is corporate for “I don't want to answer this.”`,
  `“Quick sync” is how meetings reproduce.`,
  `The meeting could have been an email. The email could have been a Slack message.`,
  `“Per my last email” is corporate for “I remember everything.”`,
  `Corporate coffee: technically coffee, spiritually hot water.`,
  `My calendar has more meetings than my life has decisions.`,
  `“Can everyone see my screen?” — The official opening ceremony of every Zoom meeting.`,
  `The Wi-Fi went down. Productivity went up.`,
  `The office printer has two settings: jammed and threatening.`,
  `“You're on mute” — the most repeated phrase in modern history.`,
  `I told my suitcase there'd be no vacations this year. Now I'm dealing with emotional baggage.`,
  `Why don't eggs tell jokes? They'd crack each other up.`,
  `I only know 25 letters of the alphabet. I don't know why.`,
  `I used to be addicted to the hokey pokey, but I turned myself around.`,
  `Why did the scarecrow win an award? He was outstanding in his field.`,
  `I told my wife she should embrace her mistakes. She hugged me.`,
  `Why don't skeletons fight each other? They don't have the guts.`,
  `I bought shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.`,
  `Why did the bicycle fall over? It was two-tired.`,
  `I asked my dog what's two minus two. He said nothing.`,
];
